# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Accessboss < Formula
  desc "Ephemeral AWS access management from the command line"
  homepage "https://github.com/webbhalsa/accessboss-cli"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/webbhalsa/accessboss-cli/releases/download/v0.0.1/accessboss-cli_darwin_amd64.tar.gz"
      sha256 "d57ddc162c44f34825bec980664a503cf03d8f5ab3ec7164f134325b1b8c1132"

      define_method(:install) do
        bin.install "accessboss"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/webbhalsa/accessboss-cli/releases/download/v0.0.1/accessboss-cli_darwin_arm64.tar.gz"
      sha256 "7bc33660ee7b93b508007f94c42baf9c82a9ccdc39294e57c4ee9c0169610ffe"

      define_method(:install) do
        bin.install "accessboss"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/webbhalsa/accessboss-cli/releases/download/v0.0.1/accessboss-cli_linux_amd64.tar.gz"
      sha256 "69b3d43123b3f5bc1d2033823916aa40b3cdb8245c203d2c5f57ee4a26f0588e"
      define_method(:install) do
        bin.install "accessboss"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/webbhalsa/accessboss-cli/releases/download/v0.0.1/accessboss-cli_linux_arm64.tar.gz"
      sha256 "21dd9c479e030d35055ade5c6d70d8ce6c1dea1b756726abbf080fb699baf22a"
      define_method(:install) do
        bin.install "accessboss"
      end
    end
  end

  def caveats
    <<~EOS
      Run 'accessboss --help' to get started.
    EOS
  end
end
