# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Accessboss < Formula
  desc "Ephemeral AWS access management from the command line"
  homepage "https://github.com/webbhalsa/accessboss-cli"
  version "0.0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/webbhalsa/accessboss-cli/releases/download/v0.0.8/accessboss-cli_darwin_amd64.tar.gz"
      sha256 "514c98603c9544bb1584707b41e39385929231a2ad327f47d0249282190377e9"

      define_method(:install) do
        bin.install "accessboss"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/webbhalsa/accessboss-cli/releases/download/v0.0.8/accessboss-cli_darwin_arm64.tar.gz"
      sha256 "66ced98868f80c79b2884907773be3e28d211ec2e672ce39d21a2e6cefb3fabf"

      define_method(:install) do
        bin.install "accessboss"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/webbhalsa/accessboss-cli/releases/download/v0.0.8/accessboss-cli_linux_amd64.tar.gz"
      sha256 "f88e529bd6c1d07bff59d40f384b6869919fc7cc41281fc0df0c89ac186adc7b"
      define_method(:install) do
        bin.install "accessboss"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/webbhalsa/accessboss-cli/releases/download/v0.0.8/accessboss-cli_linux_arm64.tar.gz"
      sha256 "38ca72e6c0bdc8fb6cee728f27f2a2d4d902725b0617a62134cdaceb071a133e"
      define_method(:install) do
        bin.install "accessboss"
      end
    end
  end

  def caveats
    <<~EOS
      Run 'accessboss --help' to get started.
    EOS
  end
end
