# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Accessboss < Formula
  desc "Ephemeral AWS access management from the command line"
  homepage "https://github.com/webbhalsa/accessboss-cli"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/webbhalsa/accessboss-cli/releases/download/v0.0.4/accessboss-cli_darwin_amd64.tar.gz"
      sha256 "98264b2735992d0b04a71c518e80d0236c27c623fa61b82f175639f5707df1b4"

      define_method(:install) do
        bin.install "accessboss"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/webbhalsa/accessboss-cli/releases/download/v0.0.4/accessboss-cli_darwin_arm64.tar.gz"
      sha256 "34846588e1bdd5e1d1ec3d2485484508d496ce7d9cd705237a4fbac386a99d83"

      define_method(:install) do
        bin.install "accessboss"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/webbhalsa/accessboss-cli/releases/download/v0.0.4/accessboss-cli_linux_amd64.tar.gz"
      sha256 "21dd082bc2eb1ae32af0d9f925dbaaf74cf14bea13be3871b4245774f28fd8e0"
      define_method(:install) do
        bin.install "accessboss"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/webbhalsa/accessboss-cli/releases/download/v0.0.4/accessboss-cli_linux_arm64.tar.gz"
      sha256 "00130222d099d8eabc5fa3e709ecb09651803e54295e9844e59aa30b30a06384"
      define_method(:install) do
        bin.install "accessboss"
      end
    end
  end

  def caveats
    <<~EOS
      Run 'accessboss --help' to get started.
    EOS
  end
end
