# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awssso < Formula
  desc "AWS SSO helper — setup and login made easy"
  homepage "https://github.com/webbhalsa/awssso"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/webbhalsa/awssso/releases/download/v0.0.6/awssso_darwin_amd64.tar.gz"
      sha256 "fd471f7d53774b0c5203820f0dd32c9473c77f599410a0cae4c53784d194e51c"

      define_method(:install) do
        bin.install "awssso"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/webbhalsa/awssso/releases/download/v0.0.6/awssso_darwin_arm64.tar.gz"
      sha256 "297ac384994a27407578abcf5cf5337a0f689d1acc2abbdca0494e6039b5f3d8"

      define_method(:install) do
        bin.install "awssso"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/webbhalsa/awssso/releases/download/v0.0.6/awssso_linux_amd64.tar.gz"
      sha256 "b66850c2b9fb61f13413bb563d0817618ea110f80241bf4f3a0ede19bf3e1117"
      define_method(:install) do
        bin.install "awssso"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/webbhalsa/awssso/releases/download/v0.0.6/awssso_linux_arm64.tar.gz"
      sha256 "dd4e2fecddb5d9efe3413977f36c9f79692acdc2da7c4160120a7715ed948e4b"
      define_method(:install) do
        bin.install "awssso"
      end
    end
  end

  def post_install
    system "#{bin}/awssso", "setup-shell"
  end

  def caveats
    <<~EOS
      Shell integration has been added to your shell rc file automatically.
      If it wasn't (e.g. you use a non-standard shell or there was an error),
      you can add it by running:
        awssso setup-shell

      Or add it to your shell rc file by hand:
        # zsh / bash:
        eval "$(awssso init)"

        # fish:
        awssso init | source
    EOS
  end
end
