# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awssso < Formula
  desc "AWS SSO helper — setup and login made easy"
  homepage "https://github.com/webbhalsa/awssso"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/webbhalsa/awssso/releases/download/v0.1.0/awssso_darwin_amd64.tar.gz"
      sha256 "db7fa288cfacf218d472a7a990541871740abc94aaf39b58f54a1dc655b5fa0c"

      define_method(:install) do
        bin.install "awssso"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/webbhalsa/awssso/releases/download/v0.1.0/awssso_darwin_arm64.tar.gz"
      sha256 "b82f0efd726079d0a67756a3e4aad1d87d8853fdef910a4dcf29973e7415a3e5"

      define_method(:install) do
        bin.install "awssso"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/webbhalsa/awssso/releases/download/v0.1.0/awssso_linux_amd64.tar.gz"
      sha256 "3575655d05af466ef82705ee68fb9a59fcabefb5628dc2b84922f5eb27a04969"
      define_method(:install) do
        bin.install "awssso"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/webbhalsa/awssso/releases/download/v0.1.0/awssso_linux_arm64.tar.gz"
      sha256 "cad35940e66dbfb0bc35474031f466857f9d2aef2c02ee6cf3a5c24fcb34915b"
      define_method(:install) do
        bin.install "awssso"
      end
    end
  end

  def post_install
    system "#{bin}/awssso", "setup-shell"
  end

  def caveats
    <<~EOS
      Shell integration has been added to your shell rc file automatically.
      If it wasn't (e.g. you use a non-standard shell or there was an error),
      you can add it by running:
        awssso setup-shell

      Or add it to your shell rc file by hand:
        # zsh / bash:
        eval "$(awssso init)"

        # fish:
        awssso init | source
    EOS
  end
end
