# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awssso < Formula
  desc "AWS SSO helper — setup and login made easy"
  homepage "https://github.com/webbhalsa/awssso"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/webbhalsa/awssso/releases/download/v0.0.5/awssso_darwin_amd64.tar.gz"
      sha256 "4813813bf13d6e399e371908771912756cb9ffbebab71875ecf619fbc94df05a"

      define_method(:install) do
        bin.install "awssso"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/webbhalsa/awssso/releases/download/v0.0.5/awssso_darwin_arm64.tar.gz"
      sha256 "60832d5d10813391f4b810232f4f8ea1b418c12f7a1969d575a51e300632cd80"

      define_method(:install) do
        bin.install "awssso"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/webbhalsa/awssso/releases/download/v0.0.5/awssso_linux_amd64.tar.gz"
      sha256 "a05e0c1ee4cde50444c9c66a6eed032d90778806a92c5bea43a44bb909d30372"
      define_method(:install) do
        bin.install "awssso"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/webbhalsa/awssso/releases/download/v0.0.5/awssso_linux_arm64.tar.gz"
      sha256 "02e12792285a8a409e453951eb0f93ea3203680d9e6a340c74ea03f9f3998865"
      define_method(:install) do
        bin.install "awssso"
      end
    end
  end

  def post_install
    system "#{bin}/awssso", "setup-shell"
  end

  def caveats
    <<~EOS
      Shell integration has been added to your shell rc file automatically.
      If it wasn't (e.g. you use a non-standard shell or there was an error),
      you can add it by running:
        awssso setup-shell

      Or add it to your shell rc file by hand:
        # zsh / bash:
        eval "$(awssso init)"

        # fish:
        awssso init | source
    EOS
  end
end
