# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dave < Formula
  desc "DAVE deployment CLI"
  homepage "https://github.com/webbhalsa/dave-cli2"
  version "0.0.9"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/webbhalsa/dave-cli2/releases/download/v0.0.9/dave-cli2_darwin_amd64.tar.gz"
      sha256 "30e2cf3e536081885b751a76ed1a3845259c8d67e135a5380bc6be54cef9b8ac"

      define_method(:install) do
        bin.install "dave"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/webbhalsa/dave-cli2/releases/download/v0.0.9/dave-cli2_darwin_arm64.tar.gz"
      sha256 "83e444bd397c9af2cdffdd4eb330004d17923d0bfa32d9e0a77c6d66b05db6da"

      define_method(:install) do
        bin.install "dave"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/webbhalsa/dave-cli2/releases/download/v0.0.9/dave-cli2_linux_amd64.tar.gz"
      sha256 "c26c98e985a090379a9b04fb4fd8d3eda801c07f417f7c938404b59197d7aa8a"
      define_method(:install) do
        bin.install "dave"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/webbhalsa/dave-cli2/releases/download/v0.0.9/dave-cli2_linux_arm64.tar.gz"
      sha256 "1f4622441da974eed1c517c64c8f85cb75efca3fbceeeeaad761872e7012337e"
      define_method(:install) do
        bin.install "dave"
      end
    end
  end

  def caveats
    <<~EOS
      If you previously had the Python-based dave CLI installed via pip3,
      you may need to remove it to avoid conflicts:

        pip3 uninstall dave

      If you still see the old binary, also remove it manually:

        rm $(which dave)

      Then re-link this installation:

        brew link --overwrite dave
    EOS
  end
end
