# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dave < Formula
  desc "DAVE deployment CLI"
  homepage "https://github.com/webbhalsa/dave-cli2"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/webbhalsa/dave-cli2/releases/download/v0.0.7/dave-cli2_darwin_amd64.tar.gz"
      sha256 "ecc56ef27a61d9ba98c0462e92cc942614bab98e92e25cc086bf071777e2e9a0"

      define_method(:install) do
        bin.install "dave"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/webbhalsa/dave-cli2/releases/download/v0.0.7/dave-cli2_darwin_arm64.tar.gz"
      sha256 "ebf181b825a784dd18991cafb640e3955a8959b38cdba0938f1379773cde5a8c"

      define_method(:install) do
        bin.install "dave"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/webbhalsa/dave-cli2/releases/download/v0.0.7/dave-cli2_linux_amd64.tar.gz"
      sha256 "242bb6e7cdd3c6e32cb2696b88a76ac7e341dcd8823097a4ee24eeabfb292389"
      define_method(:install) do
        bin.install "dave"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/webbhalsa/dave-cli2/releases/download/v0.0.7/dave-cli2_linux_arm64.tar.gz"
      sha256 "412af7d0e7cc7221e9f83181325b68cb9625bd434dda799207a9fc73b53cee12"
      define_method(:install) do
        bin.install "dave"
      end
    end
  end

  def caveats
    <<~EOS
      If you previously had the Python-based dave CLI installed via pip3,
      you may need to remove it to avoid conflicts:

        pip3 uninstall dave

      If you still see the old binary, also remove it manually:

        rm $(which dave)

      Then re-link this installation:

        brew link --overwrite dave
    EOS
  end
end
