# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dave < Formula
  desc "DAVE deployment CLI"
  homepage "https://github.com/webbhalsa/dave-cli2"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/webbhalsa/dave-cli2/releases/download/v0.1.0/dave-cli2_darwin_amd64.tar.gz"
      sha256 "c40512457dce9cb7f8f163ed8cd3b5450451b3b5a3a5bf5821074100e6fa89dd"

      define_method(:install) do
        bin.install "dave"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/webbhalsa/dave-cli2/releases/download/v0.1.0/dave-cli2_darwin_arm64.tar.gz"
      sha256 "345da3ef4871707bea6897bc1b97d1f43425901320df972fb569f32cd5eb21b2"

      define_method(:install) do
        bin.install "dave"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/webbhalsa/dave-cli2/releases/download/v0.1.0/dave-cli2_linux_amd64.tar.gz"
      sha256 "79eeb9748607e69cb4e7673afac5250d296dde128ab7bcee7e6fca1b158e9cef"
      define_method(:install) do
        bin.install "dave"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/webbhalsa/dave-cli2/releases/download/v0.1.0/dave-cli2_linux_arm64.tar.gz"
      sha256 "0d7f4cb6a852207e42d2ea0209d1a4d230db23df1ae745c6696857f950a87d39"
      define_method(:install) do
        bin.install "dave"
      end
    end
  end

  def caveats
    <<~EOS
      If you previously had the Python-based dave CLI installed via pip3,
      you may need to remove it to avoid conflicts:

        pip3 uninstall dave

      If you still see the old binary, also remove it manually:

        rm $(which dave)

      Then re-link this installation:

        brew link --overwrite dave
    EOS
  end
end
