# typed: false
# frozen_string_literal: true

# This file was generated by GitHub Actions. DO NOT EDIT.
cask "colimabar" do
  version "0.1.9"
  sha256 "84c4b840c398b7d921303d21cb7edd513e7380a9031915afd18fa3853988e0ac"

  url "https://github.com/webbhalsa/colimabar/releases/download/v#{version}/ColimaBar-#{version}.zip"
  name "ColimaBar"
  desc "Menu bar controller for colima"
  homepage "https://github.com/webbhalsa/colimabar"

  depends_on formula: "colima"
  depends_on macos: :sonoma

  app "ColimaBar.app"

  caveats <<~EOS
    ColimaBar is currently ad-hoc signed, so macOS Gatekeeper blocks
    it on first launch with a "cannot verify … free of malware" dialog
    (only Close / Move to Bin — the older right-click Open trick no
    longer works on Sequoia and later).

    Clear the quarantine attribute once, then open normally:

        xattr -d com.apple.quarantine /Applications/ColimaBar.app
        open /Applications/ColimaBar.app

    Or, if you prefer the GUI route: after the block dialog appears,
    open System Settings › Privacy & Security, scroll to the bottom
    and click Open Anyway next to ColimaBar.

    Subsequent launches work normally.

    ColimaBar wraps the `colima` CLI — installed automatically as a
    dependency of this cask.
  EOS

  zap trash: [
    "~/Library/Preferences/se.kry.ColimaBar.plist",
    "~/Library/Application Scripts/se.kry.ColimaBar",
    "~/Library/Containers/se.kry.ColimaBar",
  ]
end
