# typed: false
# frozen_string_literal: true

# This file was generated by GitHub Actions. DO NOT EDIT.
cask "colimabar" do
  version "0.1.0"
  sha256 "8b425549e264ad954d1899ee595fc280f3e2b612092b7fcc40ad3028c7a9e52d"

  url "https://github.com/webbhalsa/colimabar/releases/download/v#{version}/ColimaBar-#{version}.zip"
  name "ColimaBar"
  desc "Menu bar controller for colima"
  homepage "https://github.com/webbhalsa/colimabar"

  depends_on formula: "colima"
  depends_on macos: :sonoma

  app "ColimaBar.app"

  caveats <<~EOS
    ColimaBar is currently ad-hoc signed, so macOS Gatekeeper blocks
    it on first launch. Open it once by either:

      • right-clicking ColimaBar in Launchpad or Finder and choosing
        Open, then Open again in the dialog, or

      • running this in a terminal:
          xattr -d com.apple.quarantine /Applications/ColimaBar.app

    Subsequent launches work normally.

    ColimaBar wraps the `colima` CLI — installed automatically as a
    dependency of this cask.
  EOS

  zap trash: [
    "~/Library/Preferences/se.kry.ColimaBar.plist",
    "~/Library/Application Scripts/se.kry.ColimaBar",
    "~/Library/Containers/se.kry.ColimaBar",
  ]
end
