# This file was generated by GoReleaser. DO NOT EDIT.
cask "kryai" do
  require "download_strategy"

  class GitHubPrivateRepositoryReleaseDownloadStrategy < CurlDownloadStrategy
    def initialize(url, name, version, **meta)
      @url = url
      parse_url_pattern
      set_github_token
      meta[:headers] ||= []
      meta[:headers] << "Accept: application/octet-stream"
      meta[:headers] << "Authorization: Bearer #{@github_token}"
      ghurl = "https://api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}"
      super(ghurl, name, version, **meta)
    end

    def parse_url_pattern
      url_pattern = %r{https://github.com/([^/]+)/([^/]+)/releases/download/([^/]+)/(\S+)}
      raise CurlDownloadStrategyError, "Invalid url pattern" unless @url =~ url_pattern
      _, @owner, @repo, @tag, @filename = *@url.match(url_pattern)
    end

    def download_url
      "https://#{@github_token}@api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}"
    end

    private

    def set_github_token
      @github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
      raise CurlDownloadStrategyError, "HOMEBREW_GITHUB_API_TOKEN is required." unless @github_token
      GitHub.repository(@owner, @repo)
    end

    def asset_id
      @asset_id ||= GitHub.get_release(@owner, @repo, @tag)["assets"]
                          .find { |a| a["name"] == @filename }
                          .fetch("id") { raise CurlDownloadStrategyError, "Asset not found" }
    end
  end

  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "69246161c0f6d060106846a00f4e56e7cb55736c5ddf2c886262304a9df519b4"
      url "https://github.com/webbhalsa/kryai/releases/download/v#{version}/kryai_darwin_amd64.tar.gz",
        verified: "github.com/webbhalsa/kryai/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_arm do
      sha256 "7cc704c0b514bfc056690d60892a98fb24dd962e7d51a45814fa06218e2a3273"
      url "https://github.com/webbhalsa/kryai/releases/download/v#{version}/kryai_darwin_arm64.tar.gz",
        verified: "github.com/webbhalsa/kryai/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  on_linux do
    on_intel do
      sha256 "41881f03360f68cc71e75d8fd8627f9a11506aeef562707b60a8a0fd19a90b13"
      url "https://github.com/webbhalsa/kryai/releases/download/v#{version}/kryai_linux_amd64.tar.gz",
        verified: "github.com/webbhalsa/kryai/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_arm do
      sha256 "ed7c7fe0a768a5bc0659b5cd4bc44c03589925f6e741bbbf1b31a1cab9ce1ffe"
      url "https://github.com/webbhalsa/kryai/releases/download/v#{version}/kryai_linux_arm64.tar.gz",
        verified: "github.com/webbhalsa/kryai/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  name "kryai"
  desc "kryai CLI for local AI workflows at Kry"
  homepage "https://github.com/webbhalsa/kryai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kryai"

  # No zap stanza required

  caveats <<~EOS
    Run 'kryai --help' to get started.
  EOS
end
