# This file was generated by GoReleaser. DO NOT EDIT.
cask "kryai" do
  require "download_strategy"

  class GitHubPrivateRepositoryReleaseDownloadStrategy < CurlDownloadStrategy
    def initialize(url, name, version, **meta)
      @url = url
      parse_url_pattern
      set_github_token
      meta[:headers] ||= []
      meta[:headers] << "Accept: application/octet-stream"
      meta[:headers] << "Authorization: Bearer #{@github_token}"
      ghurl = "https://api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}"
      super(ghurl, name, version, **meta)
    end

    def parse_url_pattern
      url_pattern = %r{https://github.com/([^/]+)/([^/]+)/releases/download/([^/]+)/(\S+)}
      raise CurlDownloadStrategyError, "Invalid url pattern" unless @url =~ url_pattern
      _, @owner, @repo, @tag, @filename = *@url.match(url_pattern)
    end

    def download_url
      "https://#{@github_token}@api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}"
    end

    private

    def set_github_token
      @github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
      raise CurlDownloadStrategyError, "HOMEBREW_GITHUB_API_TOKEN is required." unless @github_token
      GitHub.repository(@owner, @repo)
    end

    def asset_id
      @asset_id ||= GitHub.get_release(@owner, @repo, @tag)["assets"]
                          .find { |a| a["name"] == @filename }
                          .fetch("id") { raise CurlDownloadStrategyError, "Asset not found" }
    end
  end

  version "0.2.6"

  on_macos do
    on_intel do
      sha256 "250aaf40a266247a11b83cf4561f98b8228cfa505ee7ebcc47d19083296341c1"
      url "https://github.com/webbhalsa/kryai/releases/download/v#{version}/kryai_darwin_amd64.tar.gz",
        verified: "github.com/webbhalsa/kryai/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_arm do
      sha256 "54374bf6336aea10103ea86a2f689305d606f5ed9646f292210464e70c1bcb5f"
      url "https://github.com/webbhalsa/kryai/releases/download/v#{version}/kryai_darwin_arm64.tar.gz",
        verified: "github.com/webbhalsa/kryai/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  on_linux do
    on_intel do
      sha256 "a5216e62615c5d5fc78161e62edbd46fcb6627885df8d3581e1ab119aa7e9cf4"
      url "https://github.com/webbhalsa/kryai/releases/download/v#{version}/kryai_linux_amd64.tar.gz",
        verified: "github.com/webbhalsa/kryai/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_arm do
      sha256 "ed3600772835620d4ce434c6f4bcabccf8e6ee4f748aac2b31acbaf86328fb65"
      url "https://github.com/webbhalsa/kryai/releases/download/v#{version}/kryai_linux_arm64.tar.gz",
        verified: "github.com/webbhalsa/kryai/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  name "kryai"
  desc "kryai CLI for local AI workflows at Kry"
  homepage "https://github.com/webbhalsa/kryai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kryai"

  # No zap stanza required

  caveats <<~EOS
    Run 'kryai --help' to get started.
  EOS
end
