# This file was generated by GoReleaser. DO NOT EDIT.
cask "kryai" do
  require "download_strategy"

  class GitHubPrivateRepositoryReleaseDownloadStrategy < CurlDownloadStrategy
    def initialize(url, name, version, **meta)
      @url = url
      parse_url_pattern
      set_github_token
      meta[:headers] ||= []
      meta[:headers] << "Accept: application/octet-stream"
      meta[:headers] << "Authorization: Bearer #{@github_token}"
      ghurl = "https://api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}"
      super(ghurl, name, version, **meta)
    end

    def parse_url_pattern
      url_pattern = %r{https://github.com/([^/]+)/([^/]+)/releases/download/([^/]+)/(\S+)}
      raise CurlDownloadStrategyError, "Invalid url pattern" unless @url =~ url_pattern
      _, @owner, @repo, @tag, @filename = *@url.match(url_pattern)
    end

    def download_url
      "https://#{@github_token}@api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}"
    end

    private

    def set_github_token
      @github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
      raise CurlDownloadStrategyError, "HOMEBREW_GITHUB_API_TOKEN is required." unless @github_token
      GitHub.repository(@owner, @repo)
    end

    def asset_id
      @asset_id ||= GitHub.get_release(@owner, @repo, @tag)["assets"]
                          .find { |a| a["name"] == @filename }
                          .fetch("id") { raise CurlDownloadStrategyError, "Asset not found" }
    end
  end

  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "53c62c9d137db3c1e27a9c6de9b03a335598f343bd5fcd4c367e865c91cdfc6f"
      url "https://github.com/webbhalsa/kryai/releases/download/v#{version}/kryai_darwin_amd64.tar.gz",
        verified: "github.com/webbhalsa/kryai/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_arm do
      sha256 "1a6d579c38a94287b90e0bdac0e2cf7feacdf5baeef535c41f9e8381aea4a4dd"
      url "https://github.com/webbhalsa/kryai/releases/download/v#{version}/kryai_darwin_arm64.tar.gz",
        verified: "github.com/webbhalsa/kryai/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  on_linux do
    on_intel do
      sha256 "48c0007cb670a29e973aaf1e190cecfd63308c9084f622bcd8982c4df40e7794"
      url "https://github.com/webbhalsa/kryai/releases/download/v#{version}/kryai_linux_amd64.tar.gz",
        verified: "github.com/webbhalsa/kryai/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
    on_arm do
      sha256 "c09ef086d0f6c393c305189bced139d7a99f82705cbfd8e9004310e29568807b"
      url "https://github.com/webbhalsa/kryai/releases/download/v#{version}/kryai_linux_arm64.tar.gz",
        verified: "github.com/webbhalsa/kryai/",
        using: GitHubPrivateRepositoryReleaseDownloadStrategy
    end
  end

  name "kryai"
  desc "kryai CLI for local AI workflows at Kry"
  homepage "https://github.com/webbhalsa/kryai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kryai"

  # No zap stanza required

  caveats <<~EOS
    Run 'kryai --help' to get started.
  EOS
end
